### ISSUE TITLE
Support VIDEO-RANGE attribute

### ISSUE THREAD

**Issue by simonerni** [carlanton/m3u8-parser#11]
Hi Anton,

After packaging my media with the Shaka Packager and trying to parse the resulting m3u8 with this parser, it throws the exception 

io.lindstrom.m3u8.parser.PlaylistParserException: Unknown key VIDEO-RANGE

VIDEO-RANGE is an attribute in a draft of RFC 8216 and has the values "PQ" or "SDR":
https://tools.ietf.org/html/draft-pantos-hls-rfc8216bis-06

Is it possible to add this attribute? I'll create a pull request for it as well.

**Comment by carlanton** [comment]
Hi Simon,

Never heard of VIDEO-RANGE before, but I did understand some of the words in RFC describing it. :)

It looks like the attribute also can be used for `EXT-X-I-FRAME-STREAM-INF`. Do you want to add that, or is shaka packager not using that?

Thanks,
Anton

**Comment by simonerni** [comment]
Hi Anton,

Yeah it's very confusing - the linked reference to the ISO standard does not help either, as you'd need to buy the standards document to even access the relevant section (TransferCharacteristics). As I understood it, it tells the player that the variant is a variant displayable by _any_ screen (SDR) or it defines some colors that are not understood (any color range commonly referred to as HDR) and marks this with `VIDEO-RANGE=PQ`.

Thanks for the quick response!

Kind Regards,
Simon

**Comment by carlanton** [comment]
Merged and released! Version 0.10 should be out on maven.org in an hour or so.

Thanks,
Anton
