### ISSUE TITLE
Add support for EXT-X-GAP

### ISSUE THREAD

**Issue by pennstatephil** [carlanton/m3u8-parser#19]
A section of a playlist can be marked missing with EXT-X-GAP. Should function similar to EXT-X-DISCONTINUITY (i.e. a boolean to insert).

https://developer.apple.com/streaming/HLS-WWDC-2017-Preliminary-Spec.pdf

**Comment by HiroyukTamura** [comment]
you can use it on [bis-07](https://github.com/carlanton/m3u8-parser/tree/bis-07) branch.

**Comment by pennstatephil** [comment]
Thanks! @carlanton any idea when this branch will be pulled into master?

**Comment by carlanton** [comment]
Well since you asked It's merged now! :) Version 0.14 will soon be available on maven. Please check if it works for you!

**Comment by pennstatephil** [comment]
Thanks!
