### ISSUE TITLE
IPTV playlist generation

### ISSUE THREAD

**Issue by ilteoood** [carlanton/m3u8-parser#21]
Hi,
I would like to create a playlist like this one:
https://github.com/tnt-wolve/m3u8-1

As you can see, the target duration isn't mandatory.
Also, I would like to set the channel logo using the tvg-logo property.
How can I make it?

**Comment by carlanton** [comment]
Hi! Interesting use of m3u8 playlists :)

EXT-X-TARGETDURATION is required in the HLS spec (RFC 8216). Maybe you can remove the tag manually after using this library?

Something like this maybe?

```
MediaPlaylist mediaPlaylist = MediaPlaylist.builder()
    .targetDuration(0)
    .addMediaSegments(
        MediaSegment.builder()
            .duration(0)
            .title("tvg-logo=\"logo-url\" ...")
            .uri("https://xyz.cloudfront.net/blah.m3u8")
            .build(),
        MediaSegment.builder()
            .duration(0)
            .title("tvg-logo=\"logo-url\" ...")
            .uri("https://xyz.cloudfront.net/foo.m3u8")
            .build())
    .build();
```

**Comment by ilteoood** [comment]
I already tought about that, but the logo should stay on the left side of the comma, while with the title property is placed on the right side

**Comment by carlanton** [comment]
Right... Well, that kind of properties doesn't align with the EXTINF format spec (https://tools.ietf.org/html/rfc8216#section-4.3.2.1). I'm not that interested to add non-standard properties to this library, sorry!

Also, if you only want to create iptv playlists (and not read them) it should be pretty straightforward with a StringBuilder or something :)
