### ISSUE TITLE
Missing sourcecode of MediaSegmentBuilder.java for m3u8-parser:0.17

### ISSUE THREAD

**Issue by k3b** [carlanton/m3u8-parser#30]
While experimenting with m8u playlist-files using m3u8-parser:0.17 from https://repo1.maven.org/maven2/io/lindstrom/m3u8-parser/0.17/ i got an excpetion

<pre>
Cannot build MediaSegment, some of required attributes are not set [duration]
java.lang.IllegalStateException: Cannot build MediaSegment, some of required attributes are not set [duration]
	at io.lindstrom.m3u8.model.MediaSegmentBuilder.build(MediaSegmentBuilder.java:325)
	at io.lindstrom.m3u8.model.MediaSegment$Builder.build(MediaSegment.java:52)
	at io.lindstrom.m3u8.parser.MediaPlaylistParser.onURI(MediaPlaylistParser.java:53)
	at io.lindstrom.m3u8.parser.MediaPlaylistParser.onURI(MediaPlaylistParser.java:32)
</pre>

When looking into the sourcecode at https://github.com/carlanton/m3u8-parser/ i saw that there is no class io.lindstrom.m3u8.model.MediaSegmentBuilder so i assume that some files are missing at https://github.com/carlanton/m3u8-parser/ that where used to create m3u8-parser:0.17

**Comment by carlanton** [comment]
Hi! All builders are generated by the Immutables library (https://immutables.github.io/). The MediaSegmentBuilder is generated from the [MediaSegment](https://github.com/carlanton/m3u8-parser/blob/master/src/main/java/io/lindstrom/m3u8/model/MediaSegment.java) interface.
You can find the actual code here https://repo1.maven.org/maven2/io/lindstrom/m3u8-parser/0.17/m3u8-parser-0.17-sources.jar or just use something like IntelliJ 👍
