### ISSUE TITLE
EXT-X-PROGRAM-DATE-TIME timestamps without colons for timezone fail to parse

### ISSUE THREAD

**Issue by brewerja** [carlanton/m3u8-parser#4]
Due to a bug in Java, the DateTimeFormatter.ISO_OFFSET_DATE_TIME doesn't parse timezones without colons. This causes the parsing of valid EXT-X-PROGRAM-DATE-TIME headers to fail.

EX: java.time.format.DateTimeParseException: Text '2022-03-17T23:00:00.000+0000' could not be parsed at index 23

https://stackoverflow.com/questions/46487403/java-8-date-and-time-parse-iso-8601-string-without-colon-in-offset

**Comment by carlanton** [comment]
Fixed in 0.8 🎉

**Comment by brewerja** [comment]
Thanks!
