### ISSUE TITLE
#EXT-X-CUE-OUT exception if tag has DURATION= or quoted value

### ISSUE THREAD

**Issue by swpalmer** [carlanton/m3u8-parser#40]
As per https://docs.aws.amazon.com/medialive/latest/ug/scte35-getting-ready-source.html#scte35-get-ready-source-support
valid formats for this tag include:

- #EXT-X-CUE-OUT:DURATION=60.000
- #EXT-X-CUE-OUT:DURATION="60.000"
- #EXT-X-CUE-OUT:60.000
- #EXT-X-CUE-OUT:"60.000"

**Comment by carlanton** [comment]
Released in 0.21!
