### ISSUE TITLE
Unrecognized field "laurl"

### ISSUE THREAD

**Issue by barsbel** [carlanton/m3u8-parser#49]
SEVERE: An exception happened during parsing MPD with message : Unrecognized field "laurl" (class io.lindstrom.mpd.data.descriptor.protection.WidewineProtection), not marked as ignorable (4 known properties: "pssh", "value", "id", "schemeIdUri"])
 at [Source: (StringReader); line: 2, column: 1108] (through reference chain: io.lindstrom.mpd.data.MPD["Period"]->java.util.ArrayList[0]->io.lindstrom.mpd.data.Period["AdaptationSet"]->java.util.ArrayList[0]->io.lindstrom.mpd.data.AdaptationSet["ContentProtection"]->java.util.ArrayList[1]->io.lindstrom.mpd.data.descriptor.protection.WidewineProtection["laurl"])

Documentation:
https://dashif-documents.azurewebsites.net/Guidelines-Security/master/Guidelines-Security.html#CPS-mpd-drm-config

**Comment by carlanton** [comment]
Pull requests are welcome :)

**Comment by barsbel** [comment]
Hi Anton,
Thanks for you quick response.
Actually, I tried to create a new Project from the existing VCS but faced the issue:
error: invalid path 'parser/src/test/resources/vectors/statodyn.php?type=mpd&pt=1376172180&tsbd=120&origmpd=http%3A%2F%2Fdash.akamaized.net%2Fdash264%2FTestCases%2F1b%2Fqualcomm%2F2%2FMultiRate.mpd&php=http%3A%2F%2Fdasher.eu5.org%2Fstatodyn.php&mpd=&debug=0&hack=.mpd'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.

With mpd-parser project downloading is everything ok.
Is mpd-parser project will be enough to create a pr with a fix?

**Comment by carlanton** [comment]
Hmm... are we talking about the mpd parser? This is the m3u8-parser! There are a few files with weird file names in the mpd-parser project. I'll remove them now...

**Comment by barsbel** [comment]
Anton, sorry. It's my mistake. This issue is related to mpd-tools project.

**Comment by barsbel** [comment]
As well as errors while downloading the project.

**Comment by carlanton** [comment]
I renamed some files, try again and see if it works better for you :)

**Comment by barsbel** [comment]
Anton, thanks a lot for you help. I will try to download mpd project. So, closing this issue.
