### ISSUE TITLE
Missing url when parsing m3u8

### ISSUE THREAD

**Issue by kShines** [carlanton/m3u8-parser#54]
When I parse a lot of m3u8 in a linux environment, I find that some of the files are missing the last url, but I can't reproduce it locally
`MediaPlaylist playlist = parser.readPlaylist(Paths.get(file.getAbsolutePath()));`
`List<MediaSegment> mediaSegments = playlist.mediaSegments();`
`LOG.info("m3u8 parser from sdk size is {}", mediaSegments.size());`

sometime is n， sometime is n-1

**Comment by carlanton** [comment]
Please re-open if this is still an issue for you!
