### ISSUE TITLE
#EXT-X-PART BYTERANGE attribute serialization doesn't comply with the HLS spec

### ISSUE THREAD

**Issue by estigma88** [carlanton/m3u8-parser#60]
### What's the issue?

[As for the HLS spec](https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis#section-4.4.4.9), the #EXT-X-PART BYTERANGE attribute:

> BYTERANGE: Indicates that the Partial Segment is a sub-range of the resource specified by the URI attribute.  **The value is a quoted-string** whose contents have the same format as the EXT-X-BYTERANGE tag: "<n>[@<o>]".  If o is not present, the sub-range begins at the next byte following the sub-range of the previous Partial Segment belonging to the same Parent Segment.

The value is a quoted-string, however, the current serialization doesn't add quotes to the BYTERANGE, as we can see [here](https://github.com/carlanton/m3u8-parser/blob/master/src/main/java/io/lindstrom/m3u8/parser/ParserUtils.java#L76).

### Expected solution

Add quotes to the BYTERANGE string

**Comment by carlanton** [comment]
Good catch! Thanks 🙏

**Comment by carlanton** [comment]
Released in version 0.25!
