### ISSUE TITLE
#EXT-X-DEFINE uses "NAME" as value of variable name

### ISSUE THREAD

**Issue by prettyls** [carlanton/m3u8-parser#63]
in master playlist, there were multiple variables in #EXT-X-DEFINE. I used variable.name().get(), the return value is "NAME", not the value of name=

for instance:
#EXT-X-DEFINE:NAME="my issue report", VALUE="variable tag issue"
the return of variable.name().get()=NAME

**Comment by carlanton** [comment]
Thanks for the report. Fixed and released in version 0.25!
